import NbE.Gluing.Base
import NbE.Gluing.Categories.Category.ContextualCartesian
import NbE.Gluing.Categories.Category.ContextualCartesianClosed
import NbE.Gluing.Categories.Category.Instance.Presheaves
import NbE.Gluing.Categories.Category.Instance.Setoids
import NbE.Gluing.Categories.Functor.ContextualCartesian
import NbE.Gluing.Categories.Functor.ContextualCartesianClosed
import NbE.Gluing.Categories.Functor.Instance.Composite
import NbE.Gluing.Categories.Functor.Instance.Identity
import NbE.Gluing.Categories.Functor.Properties
import NbE.Gluing.Contexts
import NbE.Gluing.Embedding
import NbE.Gluing.Examples
import NbE.Gluing.Glue.Base
import NbE.Gluing.Glue.Cartesian
import NbE.Gluing.Glue.CartesianClosed
import NbE.Gluing.Glue.Eval
import NbE.Gluing.Glue.Lambda
import NbE.Gluing.Glue.Relation
import NbE.Gluing.Glue.Yoga
import NbE.Gluing.Interpretation
import NbE.Gluing.Representation
import NbE.Gluing.Syntax
import NbE.Gluing.Transport
import NbE.Gluing.Transport.Functor
import NbE.Gluing.Util.Equivalence
import NbE.Gluing.Weakenings
