name: Ubuntu build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-tdpe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v17
      - name: Test
        run: nix develop --command make test
